stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/processed
    params:
    - prepare.multiplier
    metrics:
    - metrics.json:
        cache: false
  train:
    cmd: python src/train.py
    deps:
    - data/processed
    - src/train.py
    params:
    - train.lr
    outs:
    - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - models/model.pkl
    - src/evaluate.py
    metrics:
    - eval_metrics.json:
        cache: false
